In [2]:
import pandas as pd

In [3]:
# Importando os Dados

pessoa_fisica = pd.read_csv("../dados/Complementares/fatec_pessoa_fisica.csv", sep = '|', encoding='UTF-8', header = 1)
endereco_pessoa_fisica = pd.read_csv("../dados/Complementares/fatec_endereco_pessoa_fisica.csv", sep = '|', encoding='UTF-8', header = 1)
fatec_operacao = pd.read_csv("../dados/Complementares/fatec_opr.csv", sep = '|', encoding='UTF-8', header = 1)
fatec_movimento = pd.read_csv("../dados/Complementares/fatec_mvt.csv", sep = '|', encoding='UTF-8', header = 1)
fatec_pagamento = pd.read_csv("../dados/Complementares/fatec_pgt.csv", sep = '|', encoding='UTF-8', header = 1)

In [4]:
# Dados Completares

# Retirando as colunas desnecessárias
pessoa_fisica_colunas = pessoa_fisica.columns[1:len(pessoa_fisica.columns) - 1]
endereco_pessoa_fisica_colunas = endereco_pessoa_fisica.columns[1:len(endereco_pessoa_fisica.columns) - 1]
fatec_operacao_colunas = fatec_operacao.columns[1:len(fatec_operacao.columns) - 1]
fatec_movimento_colunas = fatec_movimento.columns[1:len(fatec_movimento.columns) - 1]
fatec_pagamento_colunas = fatec_pagamento.columns[1:len(fatec_pagamento.columns) - 1]

# Armazenando o nome de uma coluna de cada tabela numa váriavel
coluna_pessoa_fisica = pessoa_fisica.columns[1]
coluna_endereco_pessoa_fisica = endereco_pessoa_fisica.columns[1]
coluna_fatec_operacao = fatec_operacao.columns[1]
coluna_fatec_movimento = fatec_movimento.columns[1]
coluna_fatec_pagamento = fatec_pagamento.columns[1]

# Redefinindo os DataFrames
pessoa_fisica = pd.DataFrame(pessoa_fisica, columns = pessoa_fisica_colunas)
endereco_pessoa_fisica = pd.DataFrame(endereco_pessoa_fisica, columns = endereco_pessoa_fisica_colunas)
fatec_operacao = pd.DataFrame(fatec_operacao, columns = fatec_operacao_colunas)
fatec_movimento = pd.DataFrame(fatec_movimento, columns = fatec_movimento_colunas)
fatec_pagamento = pd.DataFrame(fatec_pagamento, columns = fatec_pagamento_colunas)

# Redefinindo o nome de cada coluna
pessoa_fisica.columns = ['id', 'cpf', 'idc_sexo', 'ano_dat_nascimento']
endereco_pessoa_fisica.columns = ['id_pessoa_fisica', 'nom_cidade', 'des_estado']
fatec_operacao.columns = ['id_opr_cad_pos', 'doc_cli', 'tip_cli', 'qtd_pcl', 'dat_vct_ult_pcl', 'vlr_ctrd_fta_tfm', 'sdo_ddr_tfm', 'vlr_ctrd', 'id_ult_rss_opr', 'id_mdl', 'cod_mdl', 'id_fnt']
fatec_movimento.columns = ['id_opr_cad_pos', 'id_mvt_cad_pos', 'dat_vct', 'qtd_pcl_vnc', 'qtd_pcl_pgr', 'vlr_tot_fat_tfm',	'vlr_min_fat_tfm', 'vlr_pcl_tfm', 'tip_mvt', 'prd']
fatec_pagamento.columns = ['id_opr_cad_pos', 'id_mvt_cad_pos', 'id_pgt_cad_pos', 'dat_pgt', 'dat_vct_tfm', 'vlr_pgt_tfm', 'cod_mdl', 'cmd']

In [5]:
# Retirando os valores nulos entre as quebras de página:
pessoa_fisica = pessoa_fisica[(pd.isna(pessoa_fisica['cpf']) != True)]
endereco_pessoa_fisica = endereco_pessoa_fisica[(pd.isna(endereco_pessoa_fisica['id_pessoa_fisica']) != True)]
fatec_operacao = fatec_operacao[(pd.isna(fatec_operacao['id_opr_cad_pos']) != True)]
fatec_movimento = fatec_movimento[(pd.isna(fatec_movimento['id_opr_cad_pos']) != True)]
fatec_pagamento = fatec_pagamento[(pd.isna(fatec_pagamento['id_opr_cad_pos']) != True)]

# Usando a váriavel anterior para retirar as quebrar de página:
pessoa_fisica = pessoa_fisica[(pessoa_fisica['id'] != coluna_pessoa_fisica)]
endereco_pessoa_fisica = endereco_pessoa_fisica[(endereco_pessoa_fisica['id_pessoa_fisica'] != coluna_endereco_pessoa_fisica)]
fatec_operacao = fatec_operacao[(fatec_operacao['id_opr_cad_pos'] != coluna_fatec_operacao)]
fatec_movimento = fatec_movimento[(fatec_movimento['id_opr_cad_pos'] != coluna_fatec_movimento)]
fatec_pagamento = fatec_pagamento[(fatec_pagamento['id_opr_cad_pos'] != coluna_fatec_pagamento)]

In [6]:
fatec_operacao

,id_opr_cad_pos,doc_cli,tip_cli,qtd_pcl,dat_vct_ult_pcl,vlr_ctrd_fta_tfm,sdo_ddr_tfm,vlr_ctrd,id_ult_rss_opr,id_mdl,cod_mdl,id_fnt
1,0f503289-dfb,87308050371,F,52,20112023,NULL,259741.1685,28511582.7,25e351cc-ec4e-4a47-861e-834f2aa1dc13,14,C01,99
2,683ea107-f2e,54355614187,F,36,06112022,140141.5236,NULL,NULL,a1f18524-8a4f-40a5-ba31-6fbff83bfd58,10,B05,99
3,d8e48899-58d,92265948819,F,NULL,NULL,NULL,0.0000,NULL,63149b03-b3bd-41e3-9b33-86661155bbaf,15,D01,179
4,5909262c-526,104455393515,F,82,20112019,NULL,1520.5905,27626512.71,40367466-b381-4452-add6-641eafb6b1be,14,C01,99
5,a2baadcc-95a,8642684152,F,65,15042020,NULL,8093.7615,26287450.65,3e99353c-df9a-4164-831d-84fff45cefdf,14,C01,99
...,...,...,...,...,...,...,...,...,...,...,...,...
3004,11bd0eb8-546,213603194469,F,NULL,NULL,NULL,2115.0240,NULL,e6c5bd30-c23a-4134-b733-c3546e9981bb,15,D01,179
3005,38634b0a-897,252169585344,F,60,25112018,145296.1440,NULL,NULL,2274cb1f-602b-4761-bea5-2ef420154a90,10,B05,99
3006,cebe727e-8b5,247391528715,F,84,10092026,NULL,187834.5642,20333074.29,5da63c6a-28be-48e4-8a4a-f71bce8a4a53,14,C01,99
3007,e6965bba-e4a,249677066973,F,47,10122021,NULL,48979.6941,30874638.3,adbd7ce7-c890-4f12-a581-7c64db1af242,14,C01,99
3008,a5d43fa5-536,258481778859,F,36,30042021,74816.1801,NULL,NULL,8340c27b-499e-4147-9d29-7268db9bd3bc,10,B05,99